### ISSUE TITLE
Sometimes conflicts with Dash to Panel

### ISSUE THREAD

**Issue by Warmuser** [dmo60/CoverflowAltTab#74] opened 2017-08-19 10:33 UTC
Hello, the extension sometimes conflict with Coverflow alt-tab: when I enable/disable these extension the panel becomes messy, the favourites disappear and the desktop seems to the point to freeze. I will report these issue also to the extension developer.

PS: I'm on Manjaro 17.0.2 GNOME 3.24.2

**Comment by p91paul** [comment] 2017-09-02 09:52
I was unable to reproduce your issues. How exactly do you trigger this? I've enabled/disabled them several times, alt-tabbed with both enabled and I didn't experience issues!

**Comment by Warmuser** [comment] 2017-09-03 08:52
@p91paul I understand. I will try to reproduce the issue and I will made a video. :)

**Comment by p91paul** [comment] 2021-04-11 14:57
Going to close this issue since at the time I was unable to reproduce it and many years have passed.
If it rehappens, please make sure to report it to dash to panel as well so we can collaborate on it.

**Closed by p91paul** 2021-04-11 14:57 UTC
