### ISSUE TITLE
gnome 42 support

### ISSUE THREAD

**Issue by rudrab** [dmo60/CoverflowAltTab#164] opened 2022-04-05 05:03 UTC
Dear developer,
Can we expect gnome 42 support of this extension?

**Comment by xerz-one** [comment] 2022-04-06 23:25
Just did some testing -- currently, the extension *almost* works, but as soon as you try to exist from the switcher, GNOME doesn't know what to do, and stays in windowing limbo. If you manage to close down all the windows, the desktop session crashes entirely.

**Comment by chrislea** [comment] 2022-04-07 00:35
I'd also like to vote for a Gnome 42 compatible version. Thanks so much for your work on this software!

**Comment by p91paul** [comment] 2022-04-10 16:38
It'll take a while for me to find time to work on this. Pull request would be really appreciated.

**Comment by appleton252** [comment] 2022-04-10 19:10
Same, this would be great. Thank you so much for this great extension!

**Comment by Neo-29** [comment] 2022-04-11 17:49
> Just did some testing -- currently, the extension _almost_ works, but as soon as you try to exit from the switcher, GNOME doesn't know what to do, and stays in windowing limbo. If you manage to close down all the windows, the desktop session crashes entirely.

same experience here 

no panel back ( disappeared) and the shell freezes as soon as I exit the switcher

**Comment by p91paul** [comment] 2022-04-11 22:49
Courtesy of @dsheeler the master branch should now be Gnome 42 compatible. I'll try and update e.g.o. as soon as I find some time.

**Comment by dsheeler** [comment] 2022-04-15 21:38
@p91paul any chance I can help with updating the extension?

**Comment by p91paul** [comment] 2022-04-16 08:16
I've seen you being more active than me here for a few releases now. If you're interested, I can have the extension ownership transferred to you on e.g.o. and get you commit rights on this repository.

**Comment by Neo-29** [comment] 2022-04-17 15:10
Hello,

I can confirm the code is good for gnome 42 (built from source)

doesn't break the shell anymore

**Comment by dsheeler** [comment] 2022-04-19 02:13
@p91paul sure!  I'd take ownership.

**Comment by p91paul** [comment] 2022-04-19 06:35
@dm60 could you please give @dsheeler commit rights on this repo?

**Comment by dmo60** [comment] 2022-04-19 17:12
> @dm60 could you please give @dsheeler commit rights on this repo?

I added you as a collaborator @dsheeler. That should do it, right? If not, let me know and I'll take a second look.

Nice to see that this extension is still alive :) Thanks @p91paul & @dsheeler !

**Comment by Alex-DA** [comment] 2022-04-28 09:34
@dsheeler it seems that the Extension still outdated at https://extensions.gnome.org/extension/97/coverflow-alt-tab/

**Comment by dsheeler** [comment] 2022-04-30 13:59
And this is officially done! I became owner and updated the version on the extensions site. \o/ :)

**Closed** 2022-04-30 14:00 UTC

**Comment by dmo60** [comment] 2024-01-09 13:01
@dsheeler I couldn't find that option anywhere in the repo settings. Do you by any chance know how to do this or have a resource at hand where it's described?

**Comment by dsheeler** [comment] 2024-03-01 23:06
@dmo60, Hi! Turns out, I did not need any special access. So that's good. I was thinking about renaming master to main, but I don't have permission to do that.

**Comment by p91paul** [comment] 2024-03-02 08:55
I do not think "renaming" a branch is a thing. You should be able to create and push locally the new main branch, then delete the remote master branch all from the command line. A setting might be required to change the default branch shown in the github gui however.

**Comment by dsheeler** [comment] 2024-03-03 09:26
Ahh, thanks @p91paul.  You're right about all that. Sorry for the confusion.  The default branch does need updating in the github settings.  

There have been various reasons here and there for me to want "administrative" access to the repo.  Like I want to change the "About" blurb on the right-hand side of the homepage.  This changing the default branch business also requires access I don't have. @dmo60, is that possible? Just would be kinda convenient sometimes.

**Comment by p91paul** [comment] 2024-03-03 11:05
Apparently, you can't: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-user-account-settings/permission-levels-for-a-personal-account-repository

**Comment by dsheeler** [comment] 2024-03-03 11:25
Couple options we could think about: transferring to an organization or transfer ownership to me. Easier would be transfer to me, but of course it's all up to @dmo60. Maybe I could make a fork be the official website for the project?

**Comment by dsheeler** [comment] 2024-03-03 11:47
Oh, and I discovered that github does allow you to rename branches through the website

**Comment by dmo60** [comment] 2024-03-03 16:26
I'm totally up for transferring it to you @dsheeler, since I haven't been involved with the project for years. I will start the process, you will receive an email and have to confirm this.

**Comment by dsheeler** [comment] 2024-03-03 21:37
I deleted the fork, @dmo60
