### ISSUE TITLE
Multiple monitors visual glitch

### ISSUE THREAD

**Issue by michalsukupcak** [dmo60/CoverflowAltTab#19] opened 2013-10-08 04:35 UTC
First of all great extension. :) However there's a small, but quite annoying visual glitch when using it on multi-monitor setup.

When Coverflow is activated, everything works as expected - switcher appears only on primary monitor, secondary (and tertiary) are left "untouched" with original windows. However, after selecting a new window in the switcher and alt key is released, the following animation affects windows on other screens as well - they "jump" to 45 degree tilt and animate back to the entire screen - basically the same animation that is going on with other windows on the main screen that are not selected - which causes a half a second blink that can get really annoying after a few hours of window switching.

My suggestion would be completely disable animations on secondary screens, if that's possible.

Unfortunately I am unable take a video of that happening, hopefully my description is clear enough.

**Comment by suokko** [comment] 2015-06-11 10:04
The problem seems to be rendering position after the animation. Everything is positioned down same amount that my secondary display resolution is higher.

My setup:
internal display at 1600x900
external display at 1280x1024 right from the primary with aligned tops

After switching whole desktop is switched down visually measured exactly the difference in heights. Meaning there is one incorrect frame where everything is rendered 124 pixel down from correct position.

The issue is made worse  by gnome-shell doing partial updates that leaves incorrect rendering in screen unless there is some update rendered to the position.

I don't know what part of code applies that transformation for the incorrect frame but possible reason might be incorrect y transformation calculation not taking correctly into account that opengl coordinate origin is bottom left corner.

**Comment by luka-n** [comment] 2016-03-02 09:56
This is still an issue making coverflow unusable on multiple monitors. Any plans to fix this?

**Comment by 4nd1m4n** [comment] 2017-04-19 04:57
I would like to add a problem/request: Is it possible to give an option to show the window switcher "copied" on all monitors currently used? Meaning that when i look at my secondary monitor i also want to see where i switch there and don't want to have to look back to my primary screen. I'm fairly certain, that the "normal" switcher showed the switching/choosing of the new window in focus on all screens.
THIS WOULD BE GREAT!

**Comment by JayBeeDe** [comment] 2019-09-25 14:32
Hi,
I have a similar issue on CentOS 7 with gnome 3 and the following configuration:
- extended desktop with 2 monitors
- 2 identical monitors (2x 1920x1080pixels, monitors are horizontally aligned => 3840x1080 pixels)
- **top bar and window bar only on the primary monitor (left monitor)**
- Coverflow alt-tab ativated and configured as follow :
![Screenshot from 2019-09-25 16-24-06](https://user-images.githubusercontent.com/17429937/65610252-5df42e80-dfb1-11e9-9d48-9a432bf07e4a.png)

Here are the reproduction steps:
- a window is maximized on the secondary monitor
- switch to another window with alt+tab (which is already on the primary monitor) :
=> It switches to the window on the primary monitor, but, until a desktop refresh occurs (seems to be around 2 minutes), any window on the secondary monitor cannot be really maximized : its size is as if there were a top bar and a window bar on the secondary monitor (which is not the case) :
![Screenshot from 2019-09-25 16-26-04](https://user-images.githubusercontent.com/17429937/65610659-f1c5fa80-dfb1-11e9-8293-d71c6bfd9f17.png)

**Comment by p91paul** [comment] 2019-09-25 17:13
@jaybeede your issue looks different, did you try with coverflow alt tab disabled? if it happens only when coverflow is enabled please open a new issue

**Comment by JayBeeDe** [comment] 2019-09-26 09:22
yes : issue #109 has been opened.

**Comment by olibre** [comment] 2020-02-14 17:25
I have a similar issue on Fedora 31 (GNOME 3.34) using a laptop connected to two other monitors (total = three screens). This issue is not reproducible when using only my laptop screen (the other monitors are disconnected).

Sometimes, pressing <kbd>Alt</kbd> + <kbd>Tab</kbd> does not produce any glitch. But often, when releasing the <kbd>Alt</kbd> key, all screens start glitching for ever, switching from previous images. Most of the time, I have to press the <kbd>Meta</kbd> key to fix the issue.

However, sometimes, one screen becomes unusable: impossible to access/use the windows in that screen. The screen can also be half frozen: the right half of my right monitor still displays the previous window. My laptop screen can also become black. In that last case, I have to <kbd>Alt</kbd> + <kbd>F2</kbd>, then <kbd>r</kbd> and <kbd>Enter</kbd> to restart GNOME.

I have attempted different configurations, but not found any workaround. I have this issue for about one or two months (I do not remember what is the change at the origin of that phenomenon).

**Comment by olibre** [comment] 2020-02-26 15:05
Today, ConverFlow works as a charm 😻 
I think the **issue is related to Linux kernel v5.4**:
* I have updated Linux kernel from v5.4 to v5.5 yesterday
* I know ConverFlow was working fine in the beginning of the year, when I was using Linux kernel 5.3
* The proprietary NVidia driver is not well integrated in Linux kernel 5.4 (my laptop was not able to boot GNOME, I had to reboot using Linux 5.3)

Thank you for this awesome GNOME extension 🏆

**Comment by p91paul** [comment] 2020-02-27 20:40
@olibre glad you solved your issue!

**Comment by p91paul** [comment] 2020-09-20 12:20
There recently was a big rewrite of many parts of this extension, courtesy of @machitgarha. From my tests with two very differently-sized monitors, this issue looks ok now. The new version is out on e.g.o for GS 3.36 and 3.38; if you experience issues with those version, please let me know and I will reopen this.

**Comment by machitgarha** [comment] 2020-09-20 13:44
@p91paul Really the current issue is fixed now!

However, you want to only support Gnome 3.36 upwards? No support for Gnome 3.30-3.34?

**Comment by p91paul** [comment] 2020-09-20 15:10
I don't have the means to test it, so I prefer to drop compatibility with older versions. Removing them from metadata.json avoids auto upgrades and potential breakage from extensions.gnome.org

**Closed** 2021-04-11 15:22 UTC
Labels: bug
