### ISSUE TITLE
coverflow not compatible with gnome-shell 3.36

### ISSUE THREAD

**Issue by rockorequin** [dmo60/CoverflowAltTab#117] opened 2020-03-03 00:32 UTC
In gnome-shell 3.35.91-1ubuntu2, pressing alt-tab with coverflow enabled does nothing.

gnome-tweaks doesn't show any error for coverflow, but this error appears in the journal:

```
Mar 03 05:37:12 xps15 gnome-shell[2053]: JS ERROR: TypeError: 

this._backgroundGroup.lower_bottom is not a function

                                         initBackground@/home/rocko/.local/share/gnome-shell/extensions/CoverflowAltTab@palatis.blogspot.com/platform.js:514:9

                                         _init@/home/rocko/.local/share/gnome-shell/extensions/CoverflowAltTab@palatis.blogspot.com/switcher.js:65:7

                                         _init@/home/rocko/.local/share/gnome-shell/extensions/CoverflowAltTab@palatis.blogspot.com/coverflowSwitcher.js:53:9

                                         Switcher@/home/rocko/.local/share/gnome-shell/extensions/CoverflowAltTab@palatis.blogspot.com/coverflowSwitcher.js:46:5

                                         _startWindowSwitcher@/home/rocko/.local/share/gnome-shell/extensions/CoverflowAltTab@palatis.blogspot.com/manager.js:142:28

```

**Comment by p91paul** [comment] 2020-03-09 22:46
Sorry, unless someone opens a pull request it is going to take some time before I can look into this issue.

**Comment by rockorequin** [comment] 2020-03-10 04:03
@p91paul: Do you know where I can find the documentation for Meta.BackgroundGroup?

**Comment by alex4401** [comment] 2020-03-10 13:54
Working on a patch. I'll see how far I can go.

**Comment by alex4401** [comment] 2020-03-10 14:57
Could someone check whether the PR works for them?

**Comment by BogdanDarius** [comment] 2020-03-10 17:02
@alex4401 I tried the PR. Sometimes it freeze and the coverflow menu doesnt show up.
Here are some errors I get:
```
JS ERROR: TypeError: this._windowTitle is null
JS ERROR: TypeError: Clutter.Vertex is not a constructor
JS ERROR: TypeError: preview.raise_top is not a function
```

**Comment by alex4401** [comment] 2020-03-10 17:10
_windowTitle error seems to be somewhat a race condition, but I hope the two other errors are now fixed in the PR. Thanks.

**Comment by BogdanDarius** [comment] 2020-03-10 17:17
Those seems to be resolved.
But I got a new error:
```
JS ERROR: ReferenceError: Graphene is not defined
```

**Comment by alex4401** [comment] 2020-03-10 17:42
Oops, forgot to import it. Sorry.

**Comment by BogdanDarius** [comment] 2020-03-10 18:06
It works very well now.
There are only two warnings but they dont crash the extension:
```
1.Some code tried to set a deprecated GObject property.
2.Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
```
Thank you!

**Comment by rockorequin** [comment] 2020-03-10 19:25
I'm seeing mixed results with this pull with my two monitor setup. Sometimes it works flawlessly, but:

- Sometimes when I press ALT-TAB, all I see is a white line down side of the dock, and when I release ALT-TAB, the screen flickers

- Sometimes when I press ALT-TAB, the windows that appear for selecting the tasks are huge, as if they are being drawn for a much larger monitor

- Occasionally after switching with the huge selection windows, X gets confused and stops drawing updates on the right-hand side of the top monitor. The lower monitor is set to 2048x1152 and the higher one to 2560x1440, and I think X is only using 2048x1440 on the top monitor when this happens. I have to restart X to fix this

**Comment by alex4401** [comment] 2020-03-10 19:38
Unsure about that - perhaps it's a change in Mutter, but I won't be able to patch this one. All hope in in p91paul for ya.

**Comment by rockorequin** [comment] 2020-03-11 01:53
There's nothing while the huge windows are up, but when I release ALT-TAB, I get a number of errors in the log like this:

```
Mar 11 09:50:08 xps15 gnome-shell[2098]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
Mar 11 09:50:08 xps15 gnome-shell[2098]: The offending signal was destroy on StBin 0x55da333d9b30.
Mar 11 09:50:14 xps15 gnome-shell[2098]: clutter_actor_remove_child: assertion 'child->priv->parent != NULL' failed
Mar 11 09:50:14 xps15 gnome-shell[2098]: Attempting to remove actor of type 'StWidget' from group of class 'Gjs_ui_layout_UiActor', but the container is not the actor's parent.

```

When the white line/flickering happens, I get errors like this:

```
Mar 11 09:41:01 xps15 gnome-shell[2098]: == Stack trace for context 0x55da323a2380 ==
Mar 11 09:41:01 xps15 gnome-shell[2098]: #0   55da3a629198 i   /home/rocko/.local/share/gnome-shell/extensions/CoverflowAltTab@dmo60.de/switcher.js:122 (7f6eee317430 @ 68)
Mar 11 09:41:01 xps15 gnome-shell[2098]: #1   55da3a6290c8 i   self-hosted:261 (7f6f1eeb3820 @ 223)
Mar 11 09:41:01 xps15 gnome-shell[2098]: #2   55da3a629020 i   /home/rocko/.local/share/gnome-shell/extensions/CoverflowAltTab@dmo60.de/switcher.js:119 (7f6eee3173a0 @ 221)
Mar 11 09:41:01 xps15 gnome-shell[2098]: #3   7ffed9c2a6d0 b   self-hosted:975 (7f6f1e6d7670 @ 392)
Mar 11 09:41:01 xps15 gnome-shell[2098]: clutter_actor_set_reactive: assertion 'CLUTTER_IS_ACTOR (actor)' failed
```

and
```

Mar 11 09:41:01 xps15 gnome-shell[2098]: clutter_actor_set_reactive: assertion 'CLUTTER_IS_ACTOR (actor)' failed
Mar 11 09:41:01 xps15 gnome-shell[2098]: == Stack trace for context 0x55da323a2380 ==
Mar 11 09:41:01 xps15 gnome-shell[2098]: #0   55da3a629538 i   resource:///org/gnome/gjs/modules/overrides/GObject.js:562 (7f6f1eead0d0 @ 25)
Mar 11 09:41:01 xps15 gnome-shell[2098]: #1   55da3a6294a0 i   resource:///org/gnome/shell/ui/tweener.js:83 (7f6f1eec6280 @ 69)
Mar 11 09:41:01 xps15 gnome-shell[2098]: #2   55da3a629420 i   resource:///org/gnome/shell/ui/tweener.js:142 (7f6f1eec6700 @ 36)
Mar 11 09:41:01 xps15 gnome-shell[2098]: #3   55da3a629380 i   resource:///org/gnome/shell/ui/tweener.js:160 (7f6f1eec68b0 @ 208)
Mar 11 09:41:01 xps15 gnome-shell[2098]: #4   55da3a6292e0 i   /home/rocko/.local/share/gnome-shell/extensions/CoverflowAltTab@dmo60.de/switcher.js:523 (7f6eee317f70 @ 108)
Mar 11 09:41:01 xps15 gnome-shell[2098]: #5   7ffed9c28f70 b   self-hosted:261 (7f6f1eeb3820 @ 223)
Mar 11 09:41:01 xps15 gnome-shell[2098]: #6   55da3a6291f0 i   /home/rocko/.local/share/gnome-shell/extensions/CoverflowAltTab@dmo60.de/switcher.js:518 (7f6eee317ee0 @ 1030)
Mar 11 09:41:01 xps15 gnome-shell[2098]: #7   55da3a629170 i   /home/rocko/.local/share/gnome-shell/extensions/CoverflowAltTab@dmo60.de/switcher.js:577 (7f6eee31b0d0 @ 17)
Mar 11 09:41:01 xps15 gnome-shell[2098]: #8   55da3a6290e0 i   /home/rocko/.local/share/gnome-shell/extensions/CoverflowAltTab@dmo60.de/switcher.js:445 (7f6eee317d30 @ 56)
Mar 11 09:41:01 xps15 gnome-shell[2098]: #9   55da3a629020 i   /home/rocko/.local/share/gnome-shell/extensions/CoverflowAltTab@dmo60.de/switcher.js:373 (7f6eee317a60 @ 398)
Mar 11 09:41:01 xps15 gnome-shell[2098]: #10   7ffed9c2a060 b   self-hosted:979 (7f6f1e6d7670 @ 440)
```

**Comment by alex4401** [comment] 2020-03-11 14:57
GC errors are something that has been showing up since 3.34 (and probably a bit earlier than that).

Seems like I'm also hit by the multi-display issue though.

**Comment by alex4401** [comment] 2020-03-11 15:14
Perhaps the assertion errors are caused by a conflict with some different extension, but I cannot reproduce them with dash-to-panel. No switcher shows for me on multi-display, but I am not familiar enough with GNOME nor the extension's internals to find a cause.

**Comment by p91paul** [comment] 2020-03-11 23:26
with multi monitors, do you all have "use always primary monitor" checked? there are known long-standing issues with multi monitor without this option.

**Comment by BogdanDarius** [comment] 2020-03-12 12:25
I think it can be merged.I have been using it for about 2 days and no crash, only those warnings.

**Comment by rockorequin** [comment] 2020-03-13 00:11
Re using just the primary monitor, the configuration window doesn't show at all for me (the journal says " Started Application launched by gnome-shell" but nothing happens), so I modified switcher.js to always select the primary monitor. Unfortunately it didn't help - I still get either the nothing shows and window flickering, or giant windows (displayed across both monitors).

**Comment by alex4401** [comment] 2020-03-13 09:57
The configuration window might not show up if you're using GNOME 3.35.91 (bug #2240), it should open on newer versions though.

Always on primary monitor also does not work for me.

**Comment by alex4401** [comment] 2020-03-13 10:22
Pushed a fix that works for me.

**Comment by p91paul** [comment] 2020-03-13 12:52
If everybody agrees, during the weekend I'm going to merge the pull request and push it to extensions.gnome.org for basic 3.36 functionality, even if multi-monitor is not fixed yet.

Given the fact I can no longer have a social life due to nationwide quarantine in Italy, I hope to solve some issues at work and then get some forced free time during which I can dedicate to this.

**Comment by rockorequin** [comment] 2020-03-15 03:57
The patch works fine in Wayland with multiple monitors btw, it's only in X that there are multi-monitor issues. xrandr only shows the one screen in Wayland:

```
Screen 0: minimum 16 x 16, current 2560 x 2592, maximum 32767 x 32767
XWAYLAND0 connected 2048x1152+0+1440 (normal left inverted right x axis y axis) 350mm x 190mm
   2048x1152     59.83*+
XWAYLAND1 connected 2560x1440+0+0 (normal left inverted right x axis y axis) 600mm x 330mm
   2560x1440     59.91*+

```

**Comment by p91paul** [comment] 2020-03-15 09:17
Merged the pull request. Leaving this issue opened for multi monitor issues!

**Comment by rockorequin** [comment] 2020-03-16 09:34
In case it helps, here is xrandr for the X session:

```
Screen 0: minimum 320 x 200, current 2560 x 2592, maximum 16384 x 16384
eDP-1 connected primary 2048x1152+0+1440 (normal left inverted right x axis y axis) 346mm x 194mm
   3840x2160     60.00 +  59.98    59.97  
   3200x1800     59.96    59.94  
   2880x1620     59.96    59.97  
   2560x1600     59.99    59.97  
   2560x1440     59.99    59.99    59.96    59.95  
   2048x1536     60.00  
   1920x1440     60.00  
   1856x1392     60.01  
   1792x1344     60.01  
   2048x1152     59.99    59.98    59.90*   59.91  
   1920x1200     59.88    59.95  
   1920x1080     60.01    59.97    59.96    59.93  
   1600x1200     60.00  
   1680x1050     59.95    59.88  
   1600x1024     60.17  
   1400x1050     59.98  
   1600x900      59.99    59.94    59.95    59.82  
   1280x1024     60.02  
   1440x900      59.89  
   1400x900      59.96    59.88  
   1280x960      60.00  
   1440x810      60.00    59.97  
   1368x768      59.88    59.85  
   1360x768      59.80    59.96  
   1280x800      59.99    59.97    59.81    59.91  
   1152x864      60.00  
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   960x540       59.96    59.99    59.63    59.82  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   800x512       60.17  
   700x525       59.98  
   800x450       59.95    59.82  
   640x512       60.02  
   720x450       59.89  
   700x450       59.96    59.88  
   640x480       60.00    59.94  
   720x405       59.51    58.99  
   684x384       59.88    59.85  
   680x384       59.80    59.96  
   640x400       59.88    59.98  
   576x432       60.06  
   640x360       59.86    59.83    59.84    59.32  
   512x384       60.00  
   512x288       60.00    59.92  
   480x270       59.63    59.82  
   400x300       60.32    56.34  
   432x243       59.92    59.57  
   320x240       60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32  
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-1 connected 2560x1440+0+0 (normal left inverted right x axis y axis) 597mm x 336mm
   2560x1440     59.95*+
   1920x1080     74.99    60.00    50.00    59.94    30.00    25.00    24.00    29.97    23.98  
   1920x1080i    60.00    50.00    59.94  
   1600x1200     60.00  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1360x768      60.02  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x576i      50.00  
   720x480       60.00    59.94  
   720x480i      60.00    59.94  
   640x480       75.00    60.00    59.94  
   720x400       70.08  
DP-2 disconnected (normal left inverted right x axis y axis)
HDMI-2 disconnected (normal left inverted right x axis y axis)

```

**Comment by rockorequin** [comment] 2020-03-16 09:36
If I change the two monitors so they have exactly the same resolution, I still see the problem.

**Comment by reuixiy** [comment] 2020-03-22 01:42
Looks like we can't cycle through the windows by the **arrow keys** now. Not sure if this is my case only.

**Comment by rockorequin** [comment] 2020-03-25 06:38
My ubuntu just upgraded gnome-shell to 3.36.0-2ubuntu1, and coverflow seems to be working fine in X11 again (hurray!).

**Comment by henrik-wittenberg** [comment] 2020-03-26 13:30
Does not work on my Manjaro installation (Gnome 3.36/X11).

It installs without any error, but then I cannot use alt-tab anymore (I have to deactivate the extension in order to use the standard alt tab again).

**Comment by alex4401** [comment] 2020-03-27 08:41
@henrik-wittenberg I think the extension wasn't uploaded yet to GNOME Extension - can you try master branch?

**Comment by henrik-wittenberg** [comment] 2020-03-27 14:15
> @henrik-wittenberg I think the extension wasn't uploaded yet to GNOME Extension - can you try master branch?

Thanks, that worked for me. :-)

**Comment by avantbored** [comment] 2020-04-05 22:28
Master branch fix did not work for me. 

Running Manjaro on Gnome 3.36.

**Comment by alex4401** [comment] 2020-04-06 08:00
@avantbored Please post your journal for /usr/bin/gnome-shell.

**Comment by avantbored** [comment] 2020-04-07 02:25
The extension does not appear in my extensions list.

I have attempted to manually install, as per the instructions on the front page.

This is the output:

`$ sudo make all
msgfmt "CoverflowAltTab@dmo60.de/locale/cs/LC_MESSAGES/coverflow.po" -o "CoverflowAltTab@dmo60.de/locale/cs/LC_MESSAGES/coverflow.mo"
msgfmt "CoverflowAltTab@dmo60.de/locale/de/LC_MESSAGES/coverflow.po" -o "CoverflowAltTab@dmo60.de/locale/de/LC_MESSAGES/coverflow.mo"
msgfmt "CoverflowAltTab@dmo60.de/locale/fr/LC_MESSAGES/coverflow.po" -o "CoverflowAltTab@dmo60.de/locale/fr/LC_MESSAGES/coverflow.mo"
msgfmt "CoverflowAltTab@dmo60.de/locale/it/LC_MESSAGES/coverflow.po" -o "CoverflowAltTab@dmo60.de/locale/it/LC_MESSAGES/coverflow.mo"
msgfmt "CoverflowAltTab@dmo60.de/locale/pt_BR/LC_MESSAGES/coverflow.po" -o "CoverflowAltTab@dmo60.de/locale/pt_BR/LC_MESSAGES/coverflow.mo"
msgfmt "CoverflowAltTab@dmo60.de/locale/zh_CN/LC_MESSAGES/coverflow.po" -o "CoverflowAltTab@dmo60.de/locale/zh_CN/LC_MESSAGES/coverflow.mo"
glib-compile-schemas "CoverflowAltTab@dmo60.de/schemas"
cp -r "CoverflowAltTab@dmo60.de" /root/.local/share/gnome-shell/extensions
cp: cannot create directory '/root/.local/share/gnome-shell/extensions': No such file or directory
make: *** [makefile:53: install] Error 1`

**Comment by alex4401** [comment] 2020-04-07 08:19
Please don't try to install the extension as root.
If you want to install it system-widely, use `sudo make all LOCALINSTALL=true`, otherwise `make all`.

**Comment by avantbored** [comment] 2020-04-07 15:19
Thank you. 

`make all` returned the same error as `No such file or directory make: *** [makefile:53: install] Error 1`. 

I then did `sudo make all LOCALINSTALL=true`, which returned the following output: 

`msgfmt "CoverflowAltTab@dmo60.de/locale/cs/LC_MESSAGES/coverflow.po" -o "CoverflowAltTab@dmo60.de/locale/cs/LC_MESSAGES/coverflow.mo"
msgfmt "CoverflowAltTab@dmo60.de/locale/de/LC_MESSAGES/coverflow.po" -o "CoverflowAltTab@dmo60.de/locale/de/LC_MESSAGES/coverflow.mo"
msgfmt "CoverflowAltTab@dmo60.de/locale/fr/LC_MESSAGES/coverflow.po" -o "CoverflowAltTab@dmo60.de/locale/fr/LC_MESSAGES/coverflow.mo"
msgfmt "CoverflowAltTab@dmo60.de/locale/it/LC_MESSAGES/coverflow.po" -o "CoverflowAltTab@dmo60.de/locale/it/LC_MESSAGES/coverflow.mo"
msgfmt "CoverflowAltTab@dmo60.de/locale/pt_BR/LC_MESSAGES/coverflow.po" -o "CoverflowAltTab@dmo60.de/locale/pt_BR/LC_MESSAGES/coverflow.mo"
msgfmt "CoverflowAltTab@dmo60.de/locale/zh_CN/LC_MESSAGES/coverflow.po" -o "CoverflowAltTab@dmo60.de/locale/zh_CN/LC_MESSAGES/coverflow.mo"
glib-compile-schemas "CoverflowAltTab@dmo60.de/schemas"
cp -r "CoverflowAltTab@dmo60.de" /usr/share/gnome-shell/extensions`

However, CoverFlow still does not appear in the available extensions to activate.

**Comment by alex4401** [comment] 2020-04-08 07:25
Make sure $HOME/.local/share/gnome-shell/extensions exists.

**Comment by avantbored** [comment] 2020-04-08 19:41
Hello,

Navigated to my `.local` directory and found a leftover installation. I removed it, repeated the Master Branch installation recommendations, and now CoverFlow works. Thank you for your assistance.

**Comment by p91paul** [comment] 2020-04-12 10:54
Extension uploaded to e.g.o., in now pending review.
I opened https://github.com/dmo60/CoverflowAltTab/issues/122 to track multi-monitor issues, so closing this one. @alex4401, many thanks, both for code and for user support here!

**Closed by p91paul** 2020-04-12 10:54 UTC
