### ISSUE TITLE
GNOME 3.30.2 crashed because of CoverflowAltTab

### ISSUE THREAD

**Issue by wotmshuaisi** [dmo60/CoverflowAltTab#92] opened 2018-11-09 14:58 UTC
fedora 29

`journalctl -xe`

```shell
Nov 09 22:54:21 **** abrt-notification[10410]: Process 4851 (gnome-shell) crashed in js::AutoEnterOOMUnsafeRegion::crash(char const*)()
-- Subject: ABRT has detected unexpected termination: gnome-shell
-- Defined-By: ABRT
-- Support: https://bugzilla.redhat.com/
-- Documentation: man:abrt(1)
-- 
-- gnome-shell killed by SIGSEGV
-- 
-- Use the abrt command-line tool for further analysis or to report
-- the problem to the appropriate support site.
Nov 09 22:54:22 **** gnome-shell[10199]: GNOME Shell started at Fri Nov 09 2018 22:54:16 GMT+0800 (CST)
Nov 09 22:54:27 **** gnome-shell[10199]: Ignoring length property that isn't a number at line 1094, col 24
Nov 09 22:54:27 **** gnome-shell[10199]: JS WARNING: [/home/***/.local/share/gnome-shell/extensions/CoverflowAltTab@palatis.blogspot.com/switcher.js 133]: reference to undefined property "legacyTray"
Nov 09 22:54:28 **** gnome-shell[10199]: JS WARNING: [/home/***/.local/share/gnome-shell/extensions/CoverflowAltTab@palatis.blogspot.com/switcher.js 530]: reference to undefined property "legacyTray"
Nov 09 22:54:28 **** gnome-shell[10199]: value "259" of type 'guint' is invalid or out of range for property 'opacity' of type 'guint'
Nov 09 22:54:28 **** gnome-shell[10199]: value "259" of type 'guint' is invalid or out of range for property 'opacity' of type 'guint'
Nov 09 22:54:28 **** gnome-shell[10199]: value "280" of type 'guint' is invalid or out of range for property 'opacity' of type 'guint'
Nov 09 22:54:28 **** gnome-shell[10199]: value "280" of type 'guint' is invalid or out of range for property 'opacity' of type 'guint'
Nov 09 22:54:28 **** gnome-shell[10199]: value "277" of type 'guint' is invalid or out of range for property 'opacity' of type 'guint'
Nov 09 22:54:28 **** gnome-shell[10199]: value "277" of type 'guint' is invalid or out of range for property 'opacity' of type 'guint'
Nov 09 22:54:28 **** gnome-shell[10199]: value "264" of type 'guint' is invalid or out of range for property 'opacity' of type 'guint'
Nov 09 22:54:28 **** gnome-shell[10199]: value "264" of type 'guint' is invalid or out of range for property 'opacity' of type 'guint'
Nov 09 22:54:28 **** gnome-shell[10199]: value "256" of type 'guint' is invalid or out of range for property 'opacity' of type 'guint'
Nov 09 22:54:28 **** gnome-shell[10199]: value "256" of type 'guint' is invalid or out of range for property 'opacity' of type 'guint'
Nov 09 22:54:29 **** gnome-shell[10199]: value "261" of type 'guint' is invalid or out of range for property 'opacity' of type 'guint'
Nov 09 22:54:29 **** gnome-shell[10199]: value "261" of type 'guint' is invalid or out of range for property 'opacity' of type 'guint'
Nov 09 22:54:29 **** gnome-shell[10199]: value "280" of type 'guint' is invalid or out of range for property 'opacity' of type 'guint'
Nov 09 22:54:29 **** gnome-shell[10199]: value "280" of type 'guint' is invalid or out of range for property 'opacity' of type 'guint'
Nov 09 22:54:29 **** gnome-shell[10199]: value "277" of type 'guint' is invalid or out of range for property 'opacity' of type 'guint'
Nov 09 22:54:29 **** gnome-shell[10199]: value "277" of type 'guint' is invalid or out of range for property 'opacity' of type 'guint'
Nov 09 22:54:29 **** gnome-shell[10199]: value "270" of type 'guint' is invalid or out of range for property 'opacity' of type 'guint'
Nov 09 22:54:29 **** gnome-shell[10199]: value "270" of type 'guint' is invalid or out of range for property 'opacity' of type 'guint'
Nov 09 22:54:29 **** gnome-shell[10199]: value "262" of type 'guint' is invalid or out of range for property 'opacity' of type 'guint'
Nov 09 22:54:29 **** gnome-shell[10199]: value "262" of type 'guint' is invalid or out of range for property 'opacity' of type 'guint'
Nov 09 22:54:29 **** gnome-shell[10199]: value "256" of type 'guint' is invalid or out of range for property 'opacity' of type 'guint'
Nov 09 22:54:29 **** gnome-shell[10199]: value "256" of type 'guint' is invalid or out of range for property 'opacity' of type 'guint'
```

**Comment by p91paul** [comment] 2018-11-10 11:06
duplicate of #90

**Closed** 2018-11-10 11:06 UTC
