### ISSUE TITLE
Coverflow/Timeline horribly broken on multi monitor

### ISSUE THREAD

**Issue by SethDusek** [dmo60/CoverflowAltTab#59] opened 2016-05-17 04:48 UTC
I was told to post this here

Hi, so I have a 1080p monitor on my left and a 1366x768p primary one, and coverflow/timeline are broken on a multi-monitor setup. Often times my screen "tears" in half while I alt tab. It's hard to explain so here is a video demonstrating it.

It doesn't happen with the normal icon + preview or any other icon + alt tab option, only with coverflow and timeline it happens.

I'm on Kernel 4.4, cinnamon version is Cinnamon 2.8.8 and I'm on intel drivers on Mesa 10.1.3 and I'll check whether this happens on NVIDIA drivers or not

**Comment by p91paul** [comment] 2016-05-17 05:48
From your wording, it looks like to me you are not using the extension, but the builtin cinnamon alt-tab option. I have good news and bad news (mostly bad, sorry). Bad news is that although cinnamon made that option by integrating this extension's code, our codebases are now separate, not really in contact unfortunately. If you install this extension following directions for manual install in this repo's home page, you are not going to solve the issue (as you can see from the issues page, it's been there for a long time), but (and here we start with the good news) you might be able to work around it as this extension offers the additional option "only show on primary monitor" which is not present in cinnamon itself I think. This bug should then be reported to the cinnamon project itself; if you do that, please post here a link to that bug report: I consider this good news since they might actually have a shot at fixing this, and I want to know that to merge such fix here as well, if and when that happens.

If you are already using the extension, and you can't reproduce with the cinnamon builtin, then there is no reason to bother cinnamon devs; just let me know.

**Comment by p91paul** [comment] 2021-04-11 15:13
I merged #145 and decided to drop Cinnamon support.
This extension, or most of it at least, should be part of cinnamon anyway; I'm aware that this extension provided more options that the cinnamon builtin, but I'm not a cinnamon user and I'm unable to provide support for it due to limited time.
If anyone wants to contribute working cinnamon code, it will be welcome. Infrastructure to support multiple platforms should be ready in platform.js.

**Closed by p91paul** 2021-04-11 15:13 UTC
