### ISSUE TITLE
First use of Alt+Tab hangs.

### ISSUE THREAD

**Issue by wildcard-f8** [dmo60/CoverflowAltTab#163] opened 2022-02-06 22:56 UTC
Whenever I boot up my system, the first time I use Alt+Tab it does the animation and gets stuck there. I click it, nothing happens. I mouse scroll, nothing happens. I Alt+Tab again, nothing happens. I have to press Esc to go back, then Alt+Tab again, but this time it works perfectly for the rest of the day until I shutdown or reboot. Then the first instance always hangs and I have to use Esc again and the cycle continues. It's always the first use of Alt+Tab. Otherwise it works great!

**Comment by p91paul** [comment] 2022-02-06 22:59
Please state your gnome shell version and if you're on Wayland or Xorg.
I most certainly cannot reproduce but maybe someone can.
Also, please check your journalctl for an error stacktrace.

**Comment by wildcard-f8** [comment] 2022-02-07 09:52
GNOME Shell 41.3
Xorg

I'm sorry, I'm not well versed in using linux so I don't know how to use journalctl to check for an error stacktrace. I'm using Manjaro btw and I tried using the new 5.15 LTS kernel and now it seems to work just fine. I'll report back if I experience it again.

**Comment by p91paul** [comment] 2022-02-10 21:24
closing for now then!

**Closed** 2022-02-10 21:24 UTC
