### ISSUE TITLE
ES6 grammar warnning ,need fix

### ISSUE THREAD

**Issue by guoqiyi** [dmo60/CoverflowAltTab#137] opened 2020-10-20 16:02 UTC
gnome-shell[564]: Some code accessed the property 'Switcher' on the module 'switcher'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.

**Comment by machitgarha** [comment] 2021-04-11 13:01
It seems it is already fixed, perhaps in #133. I think the issue is happened with a not-up-to-date version of the extension, as the pull request is merged before the current issue. However, I did a search in all files, and it seems there is only one use of the keyword `var`, in `preview.js`, which is unrelated. Plus, I checked my journalctl logs, and there the mentioned error have not happened a single time.

So I think this issue should be closed.

**Comment by p91paul** [comment] 2021-04-11 13:13
@machitgarha thanks!
I confirm I don't see it either.

**Closed by p91paul** 2021-04-11 13:13 UTC
